### ISSUE TITLE
Current version is limited to 102.0, will stop working when 102.0.1 is released

### ISSUE THREAD

**Issue by jobisoft** [marph91/thunderbird-joplin-export#10]
Hi,

your extension passed a quick functionality test and seems to be compatible with Thunderbird 102, the next major version, which has been released this week.

However, the max version setting of 102.0 is limiting this add-on to Thunderbird 102.0 and your users will not be able to use it, when Thunderbird 102.0.1 is released next week.

If you also find, that your add-on is working as expected in Thunderbird 102, please submit a new version with a max setting of 102.* (changing the value on ATN only will prevent offline installs, which do not check the updated max version setting on ATN)

If you find errors which we missed, feel free to reach out for help: 
https://developer.thunderbird.net/add-ons/community

**Comment by marph91** [comment]
Hi,

thanks for the reminder. The version setting was adapted in 43ff841f1. I will do some testing and if it works as expected, submit a new release of the add-on.

**Comment by jobisoft** [comment]
\o/

Thanks for the time and energy you put into your add-on!

**Comment by marph91** [comment]
Released with v0.0.2: https://addons.thunderbird.net/de/thunderbird/addon/joplin-export/versions/?page=1#version-0.0.2

Thanks for the fast review!
