### ISSUE TITLE
Possibly the plugin does not work with 115.3.1?

### ISSUE THREAD

**Issue by Grydpype** [marph91/thunderbird-joplin-export#23]
Dear all,

using the plugin to export a selected mail produces the message "Joplin Export succeeded, exported 0 mails". Nothing is sent to Joplin.

Running Linux Mint 21.2; Joplin 2.12.18 & Thunderbird 115.3.1.; the configuration of the plugin states "status : working"

Any suggestions?

Regards,
Oliver.

**Comment by marph91** [comment]
Hi, that's an unexpected behaviour. I will try to get a Thunderbird 115 running on my machine and check if I can reproduce.

If you don't mind, you could check in the meantime:

1. Is it same for another mail?
2. There are two ways to export. By the button at top right and by right click on the mail and selecting "Joplin Export" (probably the last entry). Does one of them work?
3. Did it work before (with some different Thunderbird version)?

**Comment by gerroon** [comment]
I am getting "please check developer console" on Win 115 with the latest version of the extension (0.0.5) According to the settings everything works.

**Comment by marph91** [comment]
Ok, thanks for checking. Then we should take a look at the developer console. Maybe that will show why exporting doesn't work.

@Grydpype, @gerroon: Could you:

1. Open the developer console (by pressing "Ctrl + Shift + I" or by the menu "Tools -> Developer Tools -> Developer Toolbox"). For me there are many messages. They can be ignored for now.
2. Export a mail and check the new output
3. Paste the output here

For me (in the successful case) it's only `Sending complete email in HTML format.`.

**Comment by Grydpype** [comment]
Exporting a mail to Joplin (several tries) does not produce any output in my console; no errors, warnings, logs, infos or debug entries ... but since I have no experience with using the console, I might just have forgotten a setting ... 

Feel free to request specific settings in the console if it helps ...

Regards,
Oliver.

**Comment by marph91** [comment]
There seem to be two different problems:

1. From grydpype: No mails to export [are detected](https://github.com/marph91/thunderbird-joplin-export/blob/master/src/background.ts#L93-L95). This means [no error message](https://github.com/marph91/thunderbird-joplin-export/blob/2e97f3757e1b24848b83ef78e2ec5b7671f490e1/src/background.ts#L107). I don't have an idea why. Specific settings should be not relevant. I will check the [Thunderbird changelog](https://webextension-api.thunderbird.net/en/stable/changes/beta115.html) later and hope to find some hint there.
2. From gerroon: There should be an [error message](https://github.com/marph91/thunderbird-joplin-export/blob/master/src/background.ts#L114-L116). I guess we can get the cause by looking at the error message.

**Comment by marph91** [comment]
Issue is tracked in #31
