### ISSUE TITLE
Still supported? 

### ISSUE THREAD

**Issue by leowankerddd** [marph91/thunderbird-joplin-export#25]
Hi,

Just loaded the plug-in a few minutes ago and it appears to work. Thank you.

Before I tell others about it I am concerned that development and support seems to have ended about a year ago. Or is it that there is nothing wrong that needs to be fixed?

Thanks.

**Comment by marph91** [comment]
> Before I tell others about it I am concerned that development and support seems to have ended about a year ago. Or is it that there is nothing wrong that needs to be fixed?

Hi, thanks for the feedback. There are some open issues, but nothing really blocking for me or other users. The plugin is in a working state, so I didn't change anything in the last months.

**Comment by leowankerddd** [comment]
That was quick!

It's only been a few minutes but the only suggestion that I would have is to add the capability to choose the notebook that you want to send it to when you click on the button in Thunderbird to send it to Joplin rather than having it hard coded to one notebook.

Similar to the way the Web Clipper lets you choose what notebook you want to clip to.


Thanks.

**Comment by marph91** [comment]
It was just good timing. There was a question about this plugin in the Joplin forum almost at the same time :D

> add the capability to choose the notebook that you want to send it to when you click on the button in Thunderbird to send it to Joplin rather than having it hard coded to one notebook

I will keep the issue open for tracking this. However, I'm not sure if it will be implemented soon. For a few notebooks it should be trivial, but if you have many notebooks it gets complicated. I. e. managing the space and indentation in a way that the user can still see something but doesn't need to scroll endlessly at the same time.

**Comment by leowankerddd** [comment]
Thank you.

I will spread the word about this plug-in to whomever I encounter that I know uses both products.

For now the only people that I know running Joplin are the people I meet in their Forum.
