### ISSUE TITLE
Joplin export to Thunderbird

### ISSUE THREAD

**Issue by RobWilkinsonUK** [marph91/thunderbird-joplin-export#29]
A notification says it has succeeded but with 0 emails. None appear in Joplin.
     
Thunderbird details:

115.10.1
20240417192958
 
release
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Thunderbird/115.10.1
Windows_NT 10.0 22000

**Comment by marph91** [comment]
Seems to be the same issue like https://github.com/marph91/thunderbird-joplin-export/issues/23. Unfortunately I wasn't able to reproduce it and don't have a clue why there aren't any mails exported (there seem to be no mails returned by [this method](https://github.com/marph91/thunderbird-joplin-export/blob/master/src/background.ts#L93-L95)).

Was the plugin working at previous Thunderbird versions for you? Or is it a fresh install?

If you don't mind, could you do a screen recording? Maybe there is something that I'm simply overlooking.

**Comment by RobWilkinsonUK** [comment]
I just checked the developer console and found nothing.
The plug in was workig prior to the Thinderbird update. I had a much earlier copy of Thunderbird because the update blew up my userChrome.css. I found someone had done a lot of work to reorganise the css for the new rev and so I updated.
Good luck in finding the problem.
Regards,
Rob

**Comment by marph91** [comment]
I just checked on another machine and in m,y Windows VM. it just worked:

- Ubuntu 22.04, Thunderbird 115.10.1, Joplin Export 0.0.6
- Windows 10, Thunderbird 115.11.0, Joplin Export 0.0.6

Also there is nothing relevant in the changenotes. I guess I can just ask in the Thunderbird forum if somebody experiences a similar problem.

Is there something you do differently to the export in the [example video](https://github.com/marph91/thunderbird-joplin-export?tab=readme-ov-file#usage)? I. e.:

1. Selecting a note
2. Clicking the export button

Side note: You could also check if you have the current version of the add-on installed: "Joplin Export 0.0.6".

**Comment by marph91** [comment]
Issue is tracked in #31
