### ISSUE TITLE
Meaning of Prefered format Plaintext or HTML

### ISSUE THREAD

**Issue by Dricc123** [marph91/thunderbird-joplin-export#30]
I understand Plaintext or HTML refers to the original email that we want to convert into markdown into Joplin.

I tried both, and the only difference is that, when HTML selected, it sometimes puts multiples lines between two paragraphs, so I chose Plaintext. But what is this field really? starting with the question Why choose a prefered format at all? and most importantly for me as a user, when to select the one or the other`?

**Comment by marph91** [comment]
During implementing I just saw that the mail can be in plaintext format, HTML or both. The setting is only useful if the mail is available in both formats. In case you need to select the format explicitly, you can use this setting and select what works better for you. If it just works, you can safely ignore it.

In the other cases, this setting doesn't have an effect. For example if the mail is only available as plaintext, but your preferred format is HTML, it will fall back to plaintext.

**Comment by Dricc123** [comment]
And this has an impact on the final outcome, in other words on the markdown that's being created in Joplin?

**Comment by marph91** [comment]
I don't have a general answer. IIRC, there were some mails that were incomplete when exported as plaintext. So I'm staying with HTML.

**Comment by Dricc123** [comment]
I'm thinking, your above explanation "The setting is only useful if" could be added in the text that gets displayed when we hoover over the i icon with the cursor.

**Comment by Dricc123** [comment]
Perfect ;-)
