### ISSUE TITLE
Version 0.0.8 does not work with Thunderbolt 128.3.1

### ISSUE THREAD

**Issue by Grydpype** [marph91/thunderbird-joplin-export#35]
**Versions**
 - OS: Linux Mint 22
 - Joplin Version 3.0.15
 - Thunderbird Version 128.3.1
 - Joplin Export add-on version 0.0.8

**Describe the bug**
Export does not work; output says "Joplin Export failed please check the developers console"

**Comment by marph91** [comment]
What's written at the developer console after you press the button? You can open it by `ctrl + shift + i` or by `Tools -> Developer Toolbox`.

**Comment by Grydpype** [comment]
After a reboot & a new ticket from Joplin it is working again; sorry for any confusion.

Cheers,
Oliver
